#include <stdint.h>

char ENGINE_CONFIG_WINDOW_TITLE[] = "My title in engine config";

uint32_t ENGINE_CONFIG_WINDOW_START_WIDTH = 320*3;
uint32_t ENGINE_CONFIG_WINDOW_START_HEIGHT = 240*3;
uint32_t ENGINE_CONFIG_WINDOW_START_X = 100;
uint32_t ENGINE_CONFIG_WINDOW_START_Y = 50;

float ENGINE_CONFIG_BACKGROUND_COLOR_R = 0.1;
float ENGINE_CONFIG_BACKGROUND_COLOR_G = 0.1;
float ENGINE_CONFIG_BACKGROUND_COLOR_B = 0.1;

float ENGINE_CONFIG_TARGET_FRAME_RATE = 60;