#define _OUTPORT_WIDTH_ (320)
#define _OUTPORT_HEIGHT_ (240)

#define _WINDOW_START_WIDTH_ (320*3)
#define _WINDOW_START_HEIGHT_ (240*3)

#define _TARGET_FRAME_DELAY_ (1000/60)

#define _DEFAULT_BACKGROUND_COLOR_R_ (0.2)
#define _DEFAULT_BACKGROUND_COLOR_G_ (0.2)
#define _DEFAULT_BACKGROUND_COLOR_B_ (0.3)

#define _DEFAULT_PILLARBOX_COLOR_R_ (0.1)
#define _DEFAULT_PILLARBOX_COLOR_G_ (0.1)
#define _DEFAULT_PILLARBOX_COLOR_B_ (0.1)