static char sun_shadow_map_frag_arr[] =
"	void main(){\n"
"	    gl_FragColor = vec4(1.0);\n"
"	}\n"
;
static char* sun_shadow_map_frag = sun_shadow_map_frag_arr;

static char sun_shadow_map_vert_arr[] =
"	#define MAX_JOINTS (20)\n"
"	\n"
"	in vec3 in_vertex_position;\n"
"	in vec2 in_vertex_texcoord;\n"
"	in vec3 in_vertex_normal;\n"
"	in ivec3 in_vertex_joint_id;\n"
"	in vec3 in_vertex_joint_wheight;\n"
"	\n"
"	uniform mat4 u_camera_world_view_projection_matrix;\n"
"	uniform mat4 u_joint_matrices[MAX_JOINTS];\n"
"	\n"
"	uniform vec3 u_position;\n"
"	uniform vec3 u_scale;\n"
"	uniform vec4 u_quat_rotation;\n"
"	\n"
"	vec4 quat_multiply(vec4 q1, vec4 q2) {\n"
"	    return vec4(\n"
"	        (q1.w*q2.x + q1.x*q2.w + q1.y*q2.z - q1.z*q2.y),\n"
"	        (q1.w*q2.y - q1.x*q2.z + q1.y*q2.w + q1.z*q2.x),\n"
"	        (q1.w*q2.z + q1.x*q2.y - q1.y*q2.x + q1.z*q2.w),\n"
"	        (q1.w*q2.w - q1.x*q2.x - q1.y*q2.y - q1.z*q2.z)\n"
"	    );\n"
"	}\n"
"	vec4 quat_conjugate(vec4 q) {\n"
"	    return vec4(-q.xyz, q.w);\n"
"	}\n"
"	vec3 rotate_vector(vec3 vec, vec4 q) {\n"
"	    vec4 q_vec = vec4(vec, 0);\n"
"	    vec4 q_res = quat_multiply(quat_multiply(q,q_vec),quat_conjugate(q));\n"
"	    return q_res.xyz;\n"
"	}\n"
"	\n"
"	void main() {\n"
"	    vec3 model_position;\n"
"	\n"
"	    if (in_vertex_joint_wheight[0] == 0 && in_vertex_joint_wheight[1] == 0 && in_vertex_joint_wheight[2] == 0) {\n"
"	        model_position = in_vertex_position;\n"
"	    }else {\n"
"	        mat4 m;\n"
"	        for (uint i = 0; i < 3; i++) {\n"
"	            m += in_vertex_joint_wheight[i] * u_joint_matrices[in_vertex_joint_id[i]];\n"
"	        }\n"
"	        model_position = vec3(vec4(in_vertex_position,1.0) * m);\n"
"	    }\n"
"	\n"
"	    vec3 position = rotate_vector(model_position*u_scale, u_quat_rotation) + u_position;\n"
"	    \n"
"	    gl_Position = vec4(position, 1.0)*u_camera_world_view_projection_matrix;\n"
"	}\n"
;
static char* sun_shadow_map_vert = sun_shadow_map_vert_arr;